version: "3.8"

services:
  arabic_dict-app:
    image: arabic_dict_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uvicorn", "arabic_dict_api:app", "--host", "0.0.0.0", "--port", "8000"]
